Output images/todos.gif

Set Shell bash

Type "clojure -M -m examples.todos"
Enter
Wait+Screen /Todo\sList/
Sleep 2s
Type "x"
Sleep 500ms
Type "xjxjx"
Sleep 500ms
Type "a"
Sleep 500ms
Type "Learn how to write vhs tests"
Enter
Sleep 500ms
Type "xk"
Sleep 500ms
Type "k"
Sleep 500ms
Type "d"
Sleep 500ms
Type "j"
Sleep 500ms
Type "k"
Sleep 500ms
Type "?"
Sleep 500ms
Type "?"
Sleep 500ms
Type "x"
Sleep 500ms
Type "q"
